server:
  port: 7777

spring:
  application:
    name: deziro
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/deziro?&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: Waxww625
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # 之后改为update
      ddl-auto: update
    show-sql: true